[package]
name = "coin_tracker"
version = "0.1.0"
authors = ["opDavi1"]
edition = "2024"
readme = "README.md"
repository = "https://github.com/opDavi1/coin-tracker-rust"
license = "GPL-3.0-or-later"
license-file = "LICENSE.md"


[dependencies]
rusqlite = "0.34.0"
